version: "3.8"

networks:
  akaunting-app:
    driver: bridge

services:
  nginx:
    image: nginx:stable-alpine
    container_name: ${APP_NAME}_nginx
    ports:
      - ${NGINX_PORT:-3000}:80
    depends_on:
      - php
    volumes:
      - ./:/var/www/html:rw
      - ./docker/logs/nginx:/var/logs/nginx:rw
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf:rw
    networks:
      - akaunting-app

  php:
    build:
      context: .
      dockerfile: prod.Dockerfile
    container_name: ${APP_NAME}_php
    ports:
      - 3002:8000
    depends_on:
      - database
    volumes:
      - ./:/var/www/html:rw
    networks:
      - akaunting-app

  database:
    image: mysql
    container_name: ${APP_NAME}_database_dev
    ports:
      - ${DB_PORT:-3306}:3306
    volumes:
      - akaunting-db:/var/lib/mysql
    environment:
      MYSQL_USER: $DB_USERNAME
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
    networks:
      - akaunting-app

volumes:
  akaunting-db: ~
